spring:
  profiles.active: default
---
spring:
  profiles: default
 
spring.datasource.url: jdbc:mysql://localhost:3306/suggestion
spring.datasource.username: suggestionuser
spring.datasource.password: passdb

#`hibernate_sequence' doesn't exist
spring.jpa.hibernate.use-new-id-generator-mappings: false

# drop n create table, good for testing, comment this in production
spring.jpa.database-platform: org.hibernate.dialect.MySQL55Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create

logging.level.org.springframework.boot: DEBUG
logging.level.org.hibernate.SQL: DEBUG


jobserver.name: server
jobserver.threads: 4
jobserver.pageSize: 100

elastic.eshost: localhost
elastic.esport: 9200
elastic.esclustername: docker-cluster
elastic.esprotocol: http
elastic.esdoctypename: documenttype
elastic.esindexname: document