spring:
  profiles.active: default
---
spring:
  profiles: default
 
spring.datasource.url: jdbc:mysql://localhost:3306/suggestion
spring.datasource.username: suggestionuser
spring.datasource.password: passdb


spring.jpa.hibernate.use-new-id-generator-mappings: false


spring.jpa.database-platform: org.hibernate.dialect.MySQL55Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create

logging.level.org.springframework.boot: TRACE
logging.level.org.hibernate.SQL: DEBUG


jobserver.name: server
jobserver.threads: 6
jobserver.pageSize: 100
jobserver.maxTasksToPoll: 5
jobserver.generateScheduleTasks: true
jobserver.scheduleEnabled: true
jobserver.pollingEnabled: true
jobserver.pollingIntervalInMillis : 5000
jobserver.numberOfTasksAllowed: 8

elastic.eshost: localhost
elastic.esport: 9200
elastic.esclustername: docker-cluster
elastic.esprotocol: http
elastic.esdoctypename: documenttype
elastic.esindexname: document

---
spring:
  profiles: test

spring.datasource.url: jdbc:h2:mem:myDb;
spring.datasource.username: suggestionuser
spring.datasource.password: passdb


spring.jpa.hibernate.use-new-id-generator-mappings: false


spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create

logging.level.org.springframework.boot: TRACE
logging.level.org.hibernate.SQL: DEBUG


jobserver.name: server
jobserver.threads: 4
jobserver.pageSize: 100
jobserver.maxTasksToPoll: 5
jobserver.generateScheduleTasks: true
jobserver.scheduleEnabled: true
jobserver.pollingEnabled: true
jobserver.pollingIntervalInMillis : 2000
jobserver.numberOfTasksAllowed : 8
jobserver.bulkDocCount : 250
jobserver.bulkSize : 10000

elastic.eshost: localhost
elastic.esport: 9200
elastic.esclustername: docker-cluster
elastic.esprotocol: http
elastic.esdoctypename: documenttype
elastic.esindexname: document

---
spring:
  profiles: container
 
logging.level.org.springframework.boot: TRACE
logging.level.org.springframework.web: TRACE
spring.datasource.url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username: ${DATABASE_USER}
spring.datasource.password: ${DATABASE_PASSWORD}
spring.datasource.initialize: true
spring.datasource.tomcat.max-wait: 20000
spring.datasource.tomcat.max-active: 50
spring.datasource.tomcat.max-idle: 20
spring.datasource.tomcat.min-idle: 15


spring.jpa.hibernate.use-new-id-generator-mappings: false


spring.jpa.database-platform: org.hibernate.dialect.MySQL55Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update


logging.level.org.hibernate.SQL: DEBUG


jobserver.name: ${SERVER_NAME}
jobserver.threads: 8
jobserver.pageSize: 100
jobserver.maxTasksToPoll: 8
jobserver.scheduleEnabled: true
jobserver.pollingEnabled: true
jobserver.pollingIntervalInMillis : 2000
jobserver.generateScheduleTasks: ${GENERATE_TASKS}
jobserver.numberOfTasksAllowed : 8
jobserver.bulkDocCount : 250
jobserver.bulkSize : 10000

elastic.eshost: ${ELASTIC_SEARCH_HOST}
elastic.esport: ${ELASTIC_SEARCH_PORT}
elastic.esclustername: docker-cluster
elastic.esprotocol: http
elastic.esdoctypename: documenttype
elastic.esindexname: document