spring:
  profiles.active: default
---
spring:
  profiles: default
 
spring.datasource.url: jdbc:mysql://localhost:3306/suggestion
spring.datasource.username: suggestionuser
spring.datasource.password: passdb


spring.jpa.hibernate.use-new-id-generator-mappings: false


spring.jpa.database-platform: org.hibernate.dialect.MySQL55Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create

logging.level.org.springframework.boot: DEBUG
logging.level.org.hibernate.SQL: DEBUG


jobserver.name: server
jobserver.threads: 4
jobserver.pageSize: 100
jobserver.maxTasksToPoll: 5

elastic.eshost: localhost
elastic.esport: 9200
elastic.esclustername: docker-cluster
elastic.esprotocol: http
elastic.esdoctypename: documenttype
elastic.esindexname: document

---
spring:
  profiles: test

spring.datasource.url: jdbc:h2:mem:myDb;
spring.datasource.username: suggestionuser
spring.datasource.password: passdb


spring.jpa.hibernate.use-new-id-generator-mappings: false


spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create

logging.level.org.springframework.boot: DEBUG
logging.level.org.hibernate.SQL: DEBUG


jobserver.name: server
jobserver.threads: 4
jobserver.pageSize: 100
jobserver.maxTasksToPoll: 5

elastic.eshost: localhost
elastic.esport: 9200
elastic.esclustername: docker-cluster
elastic.esprotocol: http
elastic.esdoctypename: documenttype
elastic.esindexname: document